#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgdata.gfdl.noaa.gov - 2021/01/28 07:49:45
# Search URL: https://esgdata.gfdl.noaa.gov/esg-search/wget/?distrib=false&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.EdayZ.ua.gr1z.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.fx.orog.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.Eday.ua.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.Eday.va.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.Eday.zg.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.Eday.wap.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.day.uas.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.day.vas.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.day.tas.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.day.hurs.gr1.v20190726|esgdata.gfdl.noaa.gov
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgdata.gfdl.noaa.gov/esg-search/wget/?distrib=false&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.EdayZ.ua.gr1z.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.fx.orog.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.Eday.ua.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.Eday.va.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.Eday.zg.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.Eday.wap.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.day.uas.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.day.vas.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.day.tas.gr1.v20190726|esgdata.gfdl.noaa.gov&dataset_id=CMIP6.CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.day.hurs.gr1.v20190726|esgdata.gfdl.noaa.gov'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/ua/gr1/v20190726/ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'SHA256' '994863ddee3d47f1cf834b17fa7a3d6d1fda52058c83902ec4902478ec398ef3'
'ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/ua/gr1/v20190726/ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'SHA256' '2b748bc59e1829d060eed91e8b2799cee9e1e9869bdeb547aef8ab8286923680'
'ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/ua/gr1/v20190726/ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'SHA256' '85518fe968395265cb693459508b970c07dfbf3b60e01a0d579839f041b4fe43'
'ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/ua/gr1/v20190726/ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'SHA256' '72e68b916d0b037ed1c7a2bf6064c682b7f0d36ab316943ede8ba2b730fc065c'
'ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/ua/gr1/v20190726/ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'SHA256' '265a16108403d2cfff3a646511fd4f909a2d888fac5beed2d66e8ef44a8f3590'
'ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/ua/gr1/v20190726/ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'SHA256' '39561c79f083b09da4e853a2cec828fb377a4622b11ae1e63545551a2f76a91d'
'ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/ua/gr1/v20190726/ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'SHA256' '715df7c99cbfc6f1239d048a433e33ef45aa8edc5b3a4627f2932ba02eda1b72'
'ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/ua/gr1/v20190726/ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'SHA256' '123979ebad06ae85d2c4bddf5c43733ea1eedc509cbfbfe1641914e6bb281886'
'ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/ua/gr1/v20190726/ua_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'SHA256' '110c86fd22cf1ab842a5b8e97bdeb90889df5bb8ba1a193e06390532455a024b'
'va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/va/gr1/v20190726/va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'SHA256' '651cd3de5723f07fbbd53b607543f0edd8d5c2b5160e5c8e61bb1b08e9fea231'
'va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/va/gr1/v20190726/va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'SHA256' '8a8e1dd3ee800de2544ac9319726e3532dce5ab6becfbf101f9841f64b07f28b'
'va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/va/gr1/v20190726/va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'SHA256' '38f6707d3e2c488d967705b9b74fb84e346973b803393a6c281b19868a00f8cd'
'va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/va/gr1/v20190726/va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'SHA256' '1a2feac8f9f97caa14c51bbfa4bfc28373e8cab8ae36caec96be55f5dd95fb7f'
'va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/va/gr1/v20190726/va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'SHA256' '14cc51246147fb0bf915be63b233496147a289e9a1eab6a8d4fe430d3e615c86'
'va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/va/gr1/v20190726/va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'SHA256' '2b293b2dc40f518476f807597beff45ef7606ddd19993e1cf69ccebb6df1875e'
'va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/va/gr1/v20190726/va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'SHA256' '734d655791eff2460e3d49bfe31fd13334778b1c9949735822e9d9bb77836b46'
'va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/va/gr1/v20190726/va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'SHA256' '29d0896a6422439660eebb18c62d01a5a6f32c05e75af4faa9d2fb9a83e69447'
'va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/va/gr1/v20190726/va_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'SHA256' '0077ee36f3f5fc9666aedab17bd0b566bb71718f646f48af18e81628f5a92354'
'wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/wap/gr1/v20190726/wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'SHA256' '4bc7e34460785c4d433840ee5fb63b0ed505db222acf1eb468a49a82560779e4'
'wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/wap/gr1/v20190726/wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'SHA256' '9f1c96df11e07bd8fc656d97c01d35a7d0b8487f0fab91a7e10ed7fafae56648'
'wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/wap/gr1/v20190726/wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'SHA256' 'dff1119dcd0377f86bb7895e2a39576ef3756564a33fd1a4b2f1bdfdc6d4f098'
'wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/wap/gr1/v20190726/wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'SHA256' '5c3d054dd255d75470c46cbd82bf7a9212c98b0cb422af22a987b4be72c06aaa'
'wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/wap/gr1/v20190726/wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'SHA256' '6bd2ac9568cc25718f2f8f2085cfd815584a13d2631d68e167ae5e8b45bab3b3'
'wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/wap/gr1/v20190726/wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'SHA256' '6961b972101317ad7a98842b09142364b80622c8a5fdb6d46bd1f44bd785c1e3'
'wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/wap/gr1/v20190726/wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'SHA256' '3077f04cb496b4ccf78ee82dcee4f4494d8e76d369f0b8c04c117d59bda09a8e'
'wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/wap/gr1/v20190726/wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'SHA256' '12ec96b01bed60f2cbd78071b73ccdebcca4321d080d944123f6cb306419eff5'
'wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/wap/gr1/v20190726/wap_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'SHA256' '07404cbc847510de4c8276b58038abe321a000e45474db94a37d63ad7e7c1054'
'zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/zg/gr1/v20190726/zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'SHA256' '7dbed94d97d8dbb2dc57879e1f75ca1393127529b5414efec4f5e1dba7682496'
'zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/zg/gr1/v20190726/zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'SHA256' 'a7749c1a75d9757eb8f6532173a6a5f5ac69b4e2da0cf3eb73db78871b30e691'
'zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/zg/gr1/v20190726/zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'SHA256' '3ee3a7dff768216fe86acc6ebb91c9c287f61996527d3302fba1ab95a0a0f835'
'zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/zg/gr1/v20190726/zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'SHA256' '07d468170a3b86788c1ba92348f8e401c533c473dc7509a0bc4996e30265d1ac'
'zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/zg/gr1/v20190726/zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'SHA256' 'c63fde4e529b7ec0c14e7302541e319755f5afd09821760a575c763b2eb6e76a'
'zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/zg/gr1/v20190726/zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'SHA256' '6231c283f580e26ed377b82c34057ac1389d440adad684b426ab53b18c2d8d22'
'zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/zg/gr1/v20190726/zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'SHA256' 'f07ad9b6865134a4828db535d4819bf8709ed85433fcb509b868d8c44368fb3c'
'zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/zg/gr1/v20190726/zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'SHA256' '74075e39dc71d64f8ef0359bf33b392e028778739fa7d468374705892f1dd9ab'
'zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Eday/zg/gr1/v20190726/zg_Eday_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'SHA256' '1fc5a97a80a9df15caaa83883b3c0b35bee325c9bbdca2c6c603b41a7c62f39f'
'ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_18500101-18691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/EdayZ/ua/gr1z/v20190726/ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_18500101-18691231.nc' 'SHA256' '17fe175006c31a5c7442c1b8664f67084750bce2180d55f87f231b6ac2ac58ba'
'ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_18700101-18891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/EdayZ/ua/gr1z/v20190726/ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_18700101-18891231.nc' 'SHA256' '07d5c0aeb18ce51594323547dbc2a6817f6183db3dd46f2f72ba8bead6062983'
'ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_18900101-19091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/EdayZ/ua/gr1z/v20190726/ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_18900101-19091231.nc' 'SHA256' '2d4eee10b5cbc64a9940d712194c1fc217494f1ff8e43e7086b423a4e0eeded1'
'ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19100101-19291231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/EdayZ/ua/gr1z/v20190726/ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19100101-19291231.nc' 'SHA256' '79cc8501ff7ea7057e987a3e6fc91d99150c94d7fa7709056d68e3f27927d240'
'ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19300101-19491231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/EdayZ/ua/gr1z/v20190726/ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19300101-19491231.nc' 'SHA256' 'ae2d2798a10f5bbd7cf7d28cc9f2fb7291bda362758b037ce78cb222ac6eaa30'
'ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19500101-19691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/EdayZ/ua/gr1z/v20190726/ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19500101-19691231.nc' 'SHA256' '251ccc1e23a73a1056d36973721b39b8b9d4b416c481b37f8eee5a5c7347bc80'
'ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19700101-19891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/EdayZ/ua/gr1z/v20190726/ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19700101-19891231.nc' 'SHA256' '7660bb4b4e9cb994e36a1abbf669e646b925a26419e3f64432bd5e5808751498'
'ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19900101-20091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/EdayZ/ua/gr1z/v20190726/ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_19900101-20091231.nc' 'SHA256' '19b9f79f75b682c812d7ffa6e890e8c80bf282c9ba1b4fbb76224caa5ff7213b'
'ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_20100101-20141231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/EdayZ/ua/gr1z/v20190726/ua_EdayZ_GFDL-ESM4_historical_r1i1p1f1_gr1z_20100101-20141231.nc' 'SHA256' '56dad81e7c25c2861f8587c64d744e9d385d33cfa0c5ba990411cb32007c923f'
'hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/hurs/gr1/v20190726/hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'SHA256' '334b34a91c27b72fc1fd03b38dd73d3a6152aedaef4f6e55a3e52eb836dc7680'
'hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/hurs/gr1/v20190726/hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'SHA256' 'f7695548c234a307257c6b2c9ba8c844ed0837844bb4068533f0ecd08cb847ac'
'hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/hurs/gr1/v20190726/hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'SHA256' 'cf97ee346e26574606759ef127c7a26e76289e5a964af48e8fd1cd45e789d81e'
'hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/hurs/gr1/v20190726/hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'SHA256' 'd093cf47ef32882afa27650ec9ee8ac9cfab4add3182b9d094578a438fbf1e34'
'hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/hurs/gr1/v20190726/hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'SHA256' '89992b13a5905e19bf1e135573c7af114c38fefe412882d87ac32b8010435bc9'
'hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/hurs/gr1/v20190726/hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'SHA256' 'ea511986f9fdc0dbbc135e5fa2e3da0b0c428cdf7a4321fe5633ddf8214287c2'
'hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/hurs/gr1/v20190726/hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'SHA256' '358080af76ab789db83f9cc000d161cef1c9d0a88fdd3ce322f53b6a22c76ae5'
'hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/hurs/gr1/v20190726/hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'SHA256' '836db03b3f2e4d36a84c80e3bf85065c04cb5da8f3fd4be4954a74f7ffd9695b'
'hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/hurs/gr1/v20190726/hurs_day_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'SHA256' 'af217efb1597fb1bc2666a85f217ebf16abb942a4fdadac7b0a4e9a4b3c46ad6'
'tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tas/gr1/v20190726/tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'SHA256' '09daf328f41bafee272ab1caf4b638cfde5140806eba9d48841e2f16125c4aac'
'tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tas/gr1/v20190726/tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'SHA256' '827bccd76d56f9eade880f4393c39b9ae373af37864f5229cd751353ed65a936'
'tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tas/gr1/v20190726/tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'SHA256' 'afd5a3b30407bb238c20a98a2148d922e5c79ed33981ae42affa975fc11bf7fa'
'tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tas/gr1/v20190726/tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'SHA256' '68e7420534128c8ce30951e32f96e2e70a1a06e41afcfb6ae44f2253ded58ee0'
'tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tas/gr1/v20190726/tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'SHA256' 'c9c3876e103b5d4c52b16f94caf8968412725038aa48cbe955655ff08cecc91a'
'tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tas/gr1/v20190726/tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'SHA256' '8ec30f38f360b8967399a994611a815c687686005affa499e5e22b22e41eb10f'
'tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tas/gr1/v20190726/tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'SHA256' 'b8e45d51f84915e5f06723f81c78de4cb5ac7f8ab9891764bced8682348fc908'
'tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tas/gr1/v20190726/tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'SHA256' '21319b76de8745787399b707790945b2e0e1703cb859e95ba24df637b33f0e6e'
'tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tas/gr1/v20190726/tas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'SHA256' 'cb28432dd1d5c22ba8dc261ebb9279e69f25deab4c5c3d7860410f17fefd9b43'
'uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/uas/gr1/v20190726/uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'SHA256' '02258dbd99fa9ca60e1ac5c39b035fdbee20ab3deb9b99a7c711cd392328fd52'
'uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/uas/gr1/v20190726/uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'SHA256' '540cf64bbbe2dbffb89504b8214fd232baa268a5efe6a94be63224743e41734e'
'uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/uas/gr1/v20190726/uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'SHA256' '831490baab75e5813695f95900be3f02cde9e24b478ff85dae440aec4cd6a758'
'uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/uas/gr1/v20190726/uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'SHA256' 'cca45cd1a8e0e5a6eec952d1a08d46a8e5e81d0195ac1c975a55fae1dc4a8a02'
'uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/uas/gr1/v20190726/uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'SHA256' 'bfffa6f8c7506542983b001d0f492c12c05989c3aac9c1bf8c581e5175d3b00f'
'uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/uas/gr1/v20190726/uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'SHA256' '44f5a8d56081ed7f95cb5b8144070b369c4cf11629903229352867d7b6329ad9'
'uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/uas/gr1/v20190726/uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'SHA256' 'c78e135cc0aaa9d5e7a4b2777a732cc235252f34200fb31d3c7fb9240c861451'
'uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/uas/gr1/v20190726/uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'SHA256' 'd9d6a7642cb0df8add3494cb4567ee4457de47ac685b33942512ccec06ffec78'
'uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/uas/gr1/v20190726/uas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'SHA256' '4ee025ee800e67d991e4d36fc25af00bf773b3a8cec8c2e793fccc3284364529'
'vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/vas/gr1/v20190726/vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18500101-18691231.nc' 'SHA256' 'bf7727bc75641e4b528b97d59e33549effc8468e49250c638dc014ef2fff8c6b'
'vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/vas/gr1/v20190726/vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18700101-18891231.nc' 'SHA256' 'c21fa3ed439698048d0c0c3c9c6e39de93e8459ac0bea5f144b465550850a0c1'
'vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/vas/gr1/v20190726/vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_18900101-19091231.nc' 'SHA256' '77fc4362bfdf2141b226018a51a4fec47a1a491b0189fd74e0c86545e8250fb8'
'vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/vas/gr1/v20190726/vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19100101-19291231.nc' 'SHA256' 'e14cf4d4eb7c4f60db3a7ff8c09a522c10cfb9d227e7a0ed5889323f450cec90'
'vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/vas/gr1/v20190726/vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19300101-19491231.nc' 'SHA256' '68f098300ebcf5154664aa8b80e26add4ab6f37e8b4351ef6b0b6110d115bdbc'
'vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/vas/gr1/v20190726/vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19500101-19691231.nc' 'SHA256' '99fc367b0d44cd5ee1a83e476191e26839b07dacb76ac2bd21756e273cacd9a5'
'vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/vas/gr1/v20190726/vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19700101-19891231.nc' 'SHA256' '3a4eb1ea4f0c588ca5369b41e1fac806de2621487acdf9ce3e5c148038845806'
'vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/vas/gr1/v20190726/vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_19900101-20091231.nc' 'SHA256' '9833ff4ba9c75e7115fd3ef9e923169274cfd34662c4bae93275eceaf87324a3'
'vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/vas/gr1/v20190726/vas_day_GFDL-ESM4_historical_r1i1p1f1_gr1_20100101-20141231.nc' 'SHA256' '81e60602ea3fa62c89a443307e0191d3852c998089ca6bce8cfd6a93378dfb6c'
'orog_fx_GFDL-ESM4_historical_r1i1p1f1_gr1.nc' 'http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/fx/orog/gr1/v20190726/orog_fx_GFDL-ESM4_historical_r1i1p1f1_gr1.nc' 'SHA256' '9a44b0f19ffbb4b18d0b5da35b842b5af6706ed5442ee66fc49b14d4ef0b0b78'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 82 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
